# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    defaults:
      run:
          working-directory: ./quirknotes/backend

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Create db dir
      run: mkdir -p data/db

    - name: Install Mongodb and Run
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-3.0.asc | sudo apt-key add -
        echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org
        sudo service mongod start
        mongod --dbpath=./data/db

    - name: Run server
      run: npm run dev

    - run: npm i
    - run: npm test
